import Box from './src/HandsomeBox';
var t1 = new Box('t1');
var t2 = new Box('t2');
t1.bind(self).setItem('name', 'jack', {mode: 'cookie', expire: -(Date.now() + 2000)}).setItem('money', 998);
t2.bind(self).setItem('age', 20);
// t1.clear();
console.log('t1.name', t1.getItem('name', true));
console.log('t1.money', t1.getItem('money'));
console.log('t2.age', t2.getItem('age'));
console.log(t1.list());
